Vagrant.configure("2") do |config|

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/bionic64"
	jenkins.vm.network "private_network", ip: "192.168.40.11"
	jenkins.vm.provider "virtualbox" do |vb|
     vb.memory = "2000"
	 vb.cpus = 2
   end
   
   jenkins.vm.provision "shell", inline: <<-SHELL
	sudo apt update
	sudo apt install openjdk-8-jdk -y
	sudo apt install maven -y

	curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
	  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
	echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
	  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
	  /etc/apt/sources.list.d/jenkins.list > /dev/null
	sudo apt update
	sudo apt-get install jenkins
	sudo systemctl enable jenkins
	sudo systemctl start jenkins


   SHELL
  end

  config.vm.define "app_staging_qa" do |nexus|
    nexus.vm.box = "geerlingguy/centos7"
    nexus.vm.network "private_network", ip: "192.168.40.12"
	nexus.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
	 vb.cpus = 2
   end
   nexus.vm.provision "shell", inline: <<-SHELL
   yum install wget java-1.8.0-openjdk.x86_64  -y
   wget https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
   
   tar xzvf apache-tomcat-8.5.78.tar.gz
   mv apache-tomcat-8.5.78 /usr/local
   /usr/local/apache-tomcat-8.5.78/bin/startup.sh
   
   SHELL
  end
end